asuproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.signin, name='login'),
    path('projects/', include('projects.urls', namespace='projects')),
    path('logout/', views.singout, name='logout'),
    path('', views.index, name='home'),
]

projects/urls.py
from django.urls import path, include
from . import views

app_name = 'projects'

urlpatterns = [
    path('project/', views.project_list, name='list'),
    path('project/new', views.project_new, name='new'),
    path('project/<int:pk>/edit', views.project_edit, name='edit'),
    path('project/<int:pk>/detail', views.project_detail,name='detail'),
    # path('project/add', views.signin, name='project_new'),
    # path('project/<int:pk>', views.singout, name='project_detail'),
    path('', views.index, name='index'),
]

keuangan/models.py
from django.db import models
from projects.models import DaftarProject

# Create your models here.

class Pemasukan(models.Model):
    nama_proj = models.ForeignKey(DaftarProject, on_delete=models.CASCADE)
    tgl_proj = models.DateField()
    nominal = models.IntegerField()
    
                     
    

projects/models.py
from django.db import models
from datetime import timedelta
import datetime, time
from django.contrib.auth.models import User

# Create your models here.
SUMBER_PROJECT = [
    (1, 'APBN'),
    (2, 'APBD TK. 1'),
    (3, 'APBD TK. 2'),
    (4, 'SWASTA'),
    (5, 'DANA INTERNASIONAL')
]

class DaftarProject(models.Model):
    nama = models.CharField(max_length=200, blank=False, verbose_name='NAMA PROJECT')
    spk = models.CharField(max_length=30, verbose_name='NO SPK')
    sumber = models.IntegerField(choices=SUMBER_PROJECT)
    alamat = models.CharField(max_length=200, blank=False)
    kota = models.CharField(max_length=100, blank=False, verbose_name='KOTA/KABUPATEN')
    provinsi = models.CharField(max_length=30)
    nilai = models.FloatField(verbose_name='NILAI PROJECT')
    tgl_buat = models.DateField(auto_now=True)
    tgl_mulai = models.DateField()
    tgl_selesai = models.DateField()
    username = models.ForeignKey(User, on_delete=models.CASCADE)

    def jatuh_tempo(self):
    
        if (self.tgl_mulai == datetime.date.today()) or (self.tgl_mulai < datetime.date.today()):
           selisih = self.tgl_selesai - datetime.date.today()
        else:
           selisih = self.tgl_selesai - self.tgl_mulai
      
        
        return (selisih.days)

        

asuproject/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from .form import UsersForm

@login_required(login_url='login')
def index(request):

    return render(request, 'index.html')

def signin(request):

    if request.method == 'POST':
        form = UsersForm(request.POST)

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            messages.success(request, f'Selamat Datang {username}')
            return redirect('home')
        else:
            messages.error(request, f'Username atau password anda salah')
            return redirect ('login')
    else:
        form = UsersForm()

    return render(request, 'login.html', {'form':form})

def singout(request):

    logout(request)
    messages.add_message(request, messages.INFO, 'Akun anda berhasil keluar')
    return redirect('login')

keuangan/views.py
from django.shortcuts import render

# Create your views here.

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .form import ProjectForm
from .models import DaftarProject
from django.contrib.auth import authenticate

# Create your views here.

# @login_required(login_url='login')
# class MainProjects():
def index(request):

    return render(request, 'index.html')

def project_list(request):

    datas = DaftarProject.objects.all()
    return render(request, 'projects/project_list.html', {'datas':datas})

def project_new(request):
    if request.method == 'POST':
        
        form = ProjectForm(request.POST)
        # print(form)
        
        if form.is_valid:
            post = form.save(commit=False)
            post.username = request.user
            post.save()

            return HttpResponseRedirect(reverse('projects:list'))
        
    else:
        form = ProjectForm()
    return render(request, 'projects/project_edit.html', {'form':form})

def project_edit(request, pk):
    master = get_object_or_404(DaftarProject, pk=pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=master)
        if form.is_valid():
            master = form.save(commit=False)
            master.save()
            return redirect('projects:detail', pk=master.pk)
    else:
        form = ProjectForm(instance=master)
        return render(request, 'projects/project_edit.html', {'form':form})

def project_detail(request, pk):
    datas = get_object_or_404(DaftarProject, pk=pk)

    return render(request, 'projects/project_detail.html', {'datas':datas})

    

projects/templates/projects/navbar.html
<ul class="nav navbar-nav">
    <li class="active">
        <a href="{% url 'home' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
    </li>
    <li class="menu-title">Dashboard Menu</li><!-- /.menu-title -->
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-male"></i>Project</a>
        <ul class="sub-menu children dropdown-menu">                            <li><i class="fa fa-plus"></i><a href="#">Input Project</a></li>
            <li><i class="fa fa-id-badge"></i><a href="ui-badges.html">Badges</a></li>
            <li><i class="fa fa-bars"></i><a href="ui-tabs.html">Tabs</a></li>

            <li><i class="fa fa-id-card-o"></i><a href="ui-cards.html">Cards</a></li>
            <li><i class="fa fa-exclamation-triangle"></i><a href="ui-alerts.html">Alerts</a></li>
            <li><i class="fa fa-spinner"></i><a href="ui-progressbar.html">Progress Bars</a></li>
            <li><i class="fa fa-fire"></i><a href="ui-modals.html">Modals</a></li>
            <li><i class="fa fa-book"></i><a href="ui-switches.html">Switches</a></li>
            <li><i class="fa fa-th"></i><a href="ui-grids.html">Grids</a></li>
            <li><i class="fa fa-file-word-o"></i><a href="ui-typgraphy.html">Typography</a></li>
        </ul>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Tables</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="fa fa-table"></i><a href="tables-basic.html">Basic Table</a></li>
            <li><i class="fa fa-table"></i><a href="tables-data.html">Data Table</a></li>
        </ul>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-th"></i>Forms</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-th"></i><a href="forms-basic.html">Basic Form</a></li>
            <li><i class="menu-icon fa fa-th"></i><a href="forms-advanced.html">Advanced Form</a></li>
        </ul>
    </li>

    <li class="menu-title">Icons</li><!-- /.menu-title -->

    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-tasks"></i>Icons</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-fort-awesome"></i><a href="font-fontawesome.html">Font Awesome</a></li>
            <li><i class="menu-icon ti-themify-logo"></i><a href="font-themify.html">Themefy Icons</a></li>
        </ul>
    </li>
    <li>
        <a href="widgets.html"> <i class="menu-icon ti-email"></i>Widgets </a>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Charts</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-line-chart"></i><a href="charts-chartjs.html">Chart JS</a></li>
            <li><i class="menu-icon fa fa-area-chart"></i><a href="charts-flot.html">Flot Chart</a></li>
            <li><i class="menu-icon fa fa-pie-chart"></i><a href="charts-peity.html">Peity Chart</a></li>
        </ul>
    </li>

    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-area-chart"></i>Maps</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-map-o"></i><a href="maps-gmap.html">Google Maps</a></li>
            <li><i class="menu-icon fa fa-street-view"></i><a href="maps-vector.html">Vector Maps</a></li>
        </ul>
    </li>
    <li class="menu-title">Extras</li><!-- /.menu-title -->
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-sign-in"></i><a href="page-login.html">Login</a></li>
            <li><i class="menu-icon fa fa-sign-in"></i><a href="page-register.html">Register</a></li>
            <li><i class="menu-icon fa fa-paper-plane"></i><a href="pages-forget.html">Forget Pass</a></li>
        </ul>
    </li>
</ul>

projects/templates/projects/project_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <strong class="card-title">Project</strong>
            </div>
            <div class="card-body">
                <!-- Credit Card -->
                <div id="pay-invoice">
                    <div class="card-body">
                        <form action="" method="POST" novalidate="novalidate">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label mb-1">{{ form.nama.label }}</label>
                                {{ form.nama }}
                                {{ form.nama.errors }}
                            </div>
                            <div class="form-group has-success">
                                <label class="control-label mb-1">{{ form.alamat.label }}</label>
                                {{ form.alamat }}
                                {{ form.alamat.errors }}
                            </div>
                            <div class="row">
                                <div class="col-4">
                                    <div class="form-group">
                                        <label class="control-label mb-1">{{ form.sumber.label }}</label>
                                        {{ form.sumber }}
                                        {{ form.sumber.errors }}
                                    </div>
                                </div>
                                <div class="col-4">
                                    <div class="form-group">
                                        <label class="control-label mb-1">{{ form.spk.label }}</label>
                                        {{ form.spk }}
                                        {{ form.spk.errors }}
                                    </div>
                                </div>
                                <div class="col-4">
                                    <div class="form-group">
                                        <label class="control-label mb-1">{{ form.kota.label }}</label>
                                        {{ form.kota }}
                                        {{ form.kota.errors }}
                                    </div>
                                </div>
                                 <div class="col-4">
                                    <div class="form-group">
                                        <label class="control-label mb-1">{{ form.provinsi.label }}</label>
                                        {{ form.provinsi }}
                                        {{ form.provinsi.errors }}
                                    </div>
                                </div>
                                 <div class="col-4">
                                    <div class="form-group">
                                        <label class="control-label mb-1">{{ form.nilai.label }}</label>
                                        {{ form.nilai }}
                                        {{ form.nilai.errors }}
                                    </div>
                                </div>
                                 <div class="col-4">
                                    <div class="form-group">
                                        <label class="control-label mb-1">{{ form.tgl_mulai.label }}</label>
                                        {{ form.tgl_mulai }}
                                        {{ form.tgl_mulai.errors }}
                                    </div>
                                </div>
                                 <div class="col-4">
                                    <div class="form-group">
                                        <label class="control-label mb-1">{{ form.tgl_selesai.label }}</label>
                                        {{ form.tgl_selesai }}
                                        {{ form.tgl_selesai.errors }}
                                    </div>
                                </div>
                            </div>
                            <div align="right">
                                <button type="submit" class="btn btn-primary">Simpan</button>
                                <a href="{% url 'projects:list' %}" class="btn btn-primary"
                                    role="button">Batal</a>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div> <!-- .card -->
    </div>
</div>



{% endblock content %}

projects/templates/projects/project_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<!-- Orders -->
<div class="orders">
    <div class="row">
        <div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="box-title">Running Project Lists</h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th class="serial">No</th>
                                    <th>Nama<br/>Proyek</th>
                                    <th>SPK</th>
                                    <th>Alamat</th>
                                    <th>Sumber<br/>Proyek</th>
                                    <th>Nilai</br>Proyek</th>
                                    <th>Kota/<br>Kabupaten</th>
                                    <th>Provinsi</th>
                                    <th>Tanggal<br/>Pengerjaan</th>
                                    <th>Tanggal<br/>Selesai</th>
                                    <th>Progress</th>
                                    <th>User</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for data in datas %}
                                <tr>
                                
                                    <td class="serial">{{ forloop.counter }}</td>
                                    
                                    <td>  <span class="name">{{data.nama}}</span> </td>
                                    <td> {{data.spk}}</td>
                                    <td> {{data.alamat}} </td>
                                    <td> {{data.get_sumber_display}} </td>
                                    
                                    <td> <span class="price">Rp.{{data.nilai|intcomma}}</span> </td>
                                    <td> {{data.kota}}</td>
                                    <td> {{data.provinsi}}</td>
                                    <td> {{data.tgl_mulai}}</td>
                                    <td> {{data.tgl_selesai}}</td>
                                    {% if data.jatuh_tempo == 0 %}
                                        <td>
                                            <span class="badge badge-complete">Complete</span>
                                        </td>
                                    {% else %}
                                        <td> {{data.jatuh_tempo}} Hari</td>
                                    {% endif %}
                                    
                                    <td> {{data.username}} </td>
                                    <td> Edit | Delete</td>
                                    
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div> <!-- /.table-stats -->
                </div>
            </div> <!-- /.card -->
        </div>  <!-- /.col-lg-8 -->

        
    </div>
</div>
<!-- /.orders -->

{% endblock content %}

templates/login.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ela Admin - HTML5 Admin Template</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="{% static 'css/cs-skin-elastic.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
</head>
<body class="bg-dark">

    <div class="sufee-login d-flex align-content-center flex-wrap">
        <div class="container">
            <div class="login-content">
                <div class="login-logo">
                    <a href="#">
                        <img class="align-content" src="{% static 'images/logo.png' %}" alt="">
                    </a>
                </div>
                <div class="login-form">
                {% if messages %}
                    {% for message in messages  %}
                        <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show">
                            <span class="badge badge-pill badge-danger">Alert!</span>
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Username</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            {{ form.password }}
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> Remember Me
                            </label>
                            <label class="pull-right">
                                <a href="#">Forgotten Password?</a>
                            </label>

                        </div>
                        <button type="submit" class="btn btn-success btn-flat m-b-30 m-t-30">Sign in</button>
                        {% comment %} <div class="social-login-content">
                            <div class="social-button">
                                <button type="button" class="btn social facebook btn-flat btn-addon mb-3"><i class="ti-facebook"></i>Sign in with facebook</button>
                                <button type="button" class="btn social twitter btn-flat btn-addon mt-2"><i class="ti-twitter"></i>Sign in with twitter</button>
                            </div>
                        </div> {% endcomment %}
                        <div class="register-link m-t-15 text-center">
                            <p>Don't have account ? <a href="#"> Sign Up Here</a></p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/navbar.html
<ul class="nav navbar-nav">
    <li class="active">
        <a href="{% url 'home' %}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
    </li>
    <li class="menu-title">Dashboard Menu</li><!-- /.menu-title -->
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-male"></i>Project</a>
        <ul class="sub-menu children dropdown-menu">                            <li><i class="fa fa-plus"></i><a href="{% url 'projects:new' %}">Input Project</a></li>
            <li><i class="fa fa-id-badge"></i><a href="ui-badges.html">Badges</a></li>
            <li><i class="fa fa-bars"></i><a href="ui-tabs.html">Tabs</a></li>

            <li><i class="fa fa-id-card-o"></i><a href="ui-cards.html">Cards</a></li>
            <li><i class="fa fa-exclamation-triangle"></i><a href="ui-alerts.html">Alerts</a></li>
            <li><i class="fa fa-spinner"></i><a href="ui-progressbar.html">Progress Bars</a></li>
            <li><i class="fa fa-fire"></i><a href="ui-modals.html">Modals</a></li>
            <li><i class="fa fa-book"></i><a href="ui-switches.html">Switches</a></li>
            <li><i class="fa fa-th"></i><a href="ui-grids.html">Grids</a></li>
            <li><i class="fa fa-file-word-o"></i><a href="ui-typgraphy.html">Typography</a></li>
        </ul>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Tables</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="fa fa-table"></i><a href="tables-basic.html">Basic Table</a></li>
            <li><i class="fa fa-table"></i><a href="tables-data.html">Data Table</a></li>
        </ul>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-th"></i>Forms</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-th"></i><a href="forms-basic.html">Basic Form</a></li>
            <li><i class="menu-icon fa fa-th"></i><a href="forms-advanced.html">Advanced Form</a></li>
        </ul>
    </li>

    <li class="menu-title">Icons</li><!-- /.menu-title -->

    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-tasks"></i>Icons</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-fort-awesome"></i><a href="font-fontawesome.html">Font Awesome</a></li>
            <li><i class="menu-icon ti-themify-logo"></i><a href="font-themify.html">Themefy Icons</a></li>
        </ul>
    </li>
    <li>
        <a href="widgets.html"> <i class="menu-icon ti-email"></i>Widgets </a>
    </li>
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Charts</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-line-chart"></i><a href="charts-chartjs.html">Chart JS</a></li>
            <li><i class="menu-icon fa fa-area-chart"></i><a href="charts-flot.html">Flot Chart</a></li>
            <li><i class="menu-icon fa fa-pie-chart"></i><a href="charts-peity.html">Peity Chart</a></li>
        </ul>
    </li>

    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-area-chart"></i>Maps</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-map-o"></i><a href="maps-gmap.html">Google Maps</a></li>
            <li><i class="menu-icon fa fa-street-view"></i><a href="maps-vector.html">Vector Maps</a></li>
        </ul>
    </li>
    <li class="menu-title">Extras</li><!-- /.menu-title -->
    <li class="menu-item-has-children dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
        <ul class="sub-menu children dropdown-menu">
            <li><i class="menu-icon fa fa-sign-in"></i><a href="page-login.html">Login</a></li>
            <li><i class="menu-icon fa fa-sign-in"></i><a href="page-register.html">Register</a></li>
            <li><i class="menu-icon fa fa-paper-plane"></i><a href="pages-forget.html">Forget Pass</a></li>
        </ul>
    </li>
</ul>